# -*- coding: utf-8 -*-
"""农时智能日历 — 预置种子数据（v2：按物候期与生育阶段编排）

【数据性质】本模块是农时日历的**唯一事实源**，由 `database._seed_farming()` 幂等写入
farming_products / farming_phenophases / farming_tasks，再由 `app.py` 的 agriculture 接口对外提供。

【v2 相对 v1 的变化】
  - 日期不再由「分类 -> 旬」的机械规则推导，改为**逐条按物候期与生育阶段编排**
    （如荔枝控梢促花须在末次秋梢老熟后、水稻穗肥须在幼穗分化期）。
  - 修正 4 处实质性农艺错误：荔枝控梢促花（9月 -> 11月）、水稻穗肥施用（7月 -> 9月）、
    水稻晒田控苗（由「不指定日期」改为明确窗口）、龙眼控梢的表述边界。
  - 补入 5 条缺失任务：水稻「晚稻播种育秧」（原任务集缺少晚稻起点），以及
    水产「水霉病预防」「增氧设备检修」、水稻「灌浆期叶面施肥」、蔬菜「秋茬育苗」——
    补齐后 6 个作物在 12 个月中每月都有固定日期节点，不再出现整月空白。
  - 每条任务新增 `source_key`（指向 FARMING_SOURCES）与 `date_basis`（日期依据）。
  - 【撰写约束】`date_basis` 会**直接展示给终端用户**，只写「为什么是这个时间」的农艺逻辑，
    不得写入内部修订说明、原始编排错误、审阅批注等；修订记录统一放《农时日历待核清单.md》。
    v1→v2 的 4 处农艺修正（荔枝控梢促花 9月→11月、水稻穗肥 7月→9月、水稻晒田改明确窗口、
    龙眼控梢表述边界）已记入该文档「v2 修订记录」一节。

【v3 相对 v2 的变化】
  - 补入**柑橘、香蕉**两个作物（6 作物 → 8 作物），使「顶部作物卡 / 农时智能日历」的作物口径
    与「病虫害诊断面板 / 常见病虫害速查」一致（缺陷 A3）。此前柑橘、香蕉只存在于后两者，
    `GET /api/agriculture/calendar/citrus` 与 `/calendar/banana` 均返回 404。
  - 新增条目同样属于**依公开资料编排的参考值**：`is_verified` 一律 0、`doc_no` 一律「待核」，
    逐条依据记入《农时日历待核清单.md》，须由农技人员复核后回填。

【重要】source_key 只登记**来源方向**（机构 + 文件类型），`doc_no` 一律为「待核」。
  doc_type / doc_no 具体标准号与版本必须由农技人员核实后填写，代码侧不得凭空编造。
  界面据此提示「依据某类技术资料编排，文号与执行细则待复核」。

【复核流程】逐条依据见《农时日历待核清单.md》。农技人员确认某条日期无误后，
  在库中把该行 `is_verified` 置 1，界面上的「约」与该作物当月的推算提示条会自动收起。
"""


FARMING_PRODUCTS = [
    {'id': 'lychee', 'name': '荔枝', 'icon': 'apple-alt', 'summary': '广东特色水果', 'sort_order': 1},
    {'id': 'longan', 'name': '龙眼', 'icon': 'circle', 'summary': '岭南佳果', 'sort_order': 2},
    # v3 新增：与诊断面板 / 病虫害速查的作物口径对齐（A3）。图标取 Font Awesome 6 免费集中
    # 语义最近的两个 —— lemon（柑橘）、leaf（香蕉叶片），免费集没有香蕉图标。
    {'id': 'citrus', 'name': '柑橘', 'icon': 'lemon', 'summary': '广东大宗水果', 'sort_order': 3},
    {'id': 'banana', 'name': '香蕉', 'icon': 'leaf', 'summary': '岭南特色蕉类', 'sort_order': 4},
    {'id': 'aquatic', 'name': '水产养殖', 'icon': 'fish', 'summary': '鱼虾蟹贝', 'sort_order': 5},
    {'id': 'rice', 'name': '水稻', 'icon': 'seedling', 'summary': '主要粮食作物', 'sort_order': 6},
    {'id': 'tea', 'name': '茶叶', 'icon': 'mug-hot', 'summary': '广东名茶', 'sort_order': 7},
    {'id': 'vegetable', 'name': '蔬菜', 'icon': 'carrot', 'summary': '时令蔬菜', 'sort_order': 8},
]

# 任务分类标签
FARMING_CATEGORY_LABELS = {'fertilize': '施肥', 'pest': '植保', 'harvest': '采收', 'manage': '管理', 'water': '水分'}

# 数据来源登记表
#   doc_no 统一为「待核」：本条仅登记来源方向（机构 + 文件类型），
#   具体标准号/文号与版本须由农技人员复核时补全，不得凭空填写。
FARMING_SOURCES = [
    {
        'key': 'GD-LYCHEE-TG', 'name': '荔枝生产技术规程',
        'org': '广东省市场监督管理局', 'doc_type': '地方标准',
        'doc_no': '待核', 'url': 'https://dbba.sacinfo.org.cn/',
    },
    {
        'key': 'GD-LONGAN-TG', 'name': '龙眼生产技术规程',
        'org': '广东省市场监督管理局', 'doc_type': '地方标准',
        'doc_no': '待核', 'url': 'https://dbba.sacinfo.org.cn/',
    },
    {
        'key': 'CARS-LZ', 'name': '荔枝龙眼栽培管理技术要点',
        'org': '农业农村部 国家荔枝龙眼产业技术体系', 'doc_type': '产业技术体系',
        'doc_no': '待核', 'url': 'https://www.cars33.cn/',
    },
    {
        'key': 'MOA-RICE-TG', 'name': '水稻生产技术规程与育插秧技术指导意见',
        'org': '农业农村部 / 全国农业技术推广服务中心', 'doc_type': '行业标准与技术指导',
        'doc_no': '待核', 'url': 'http://www.natesc.org.cn/',
    },
    {
        'key': 'GD-TEA-TG', 'name': '茶树栽培技术规程',
        'org': '广东省市场监督管理局', 'doc_type': '地方标准',
        'doc_no': '待核', 'url': 'https://dbba.sacinfo.org.cn/',
    },
    {
        'key': 'GD-VEG-TG', 'name': '蔬菜生产技术规程',
        'org': '广东省市场监督管理局', 'doc_type': '地方标准',
        'doc_no': '待核', 'url': 'https://dbba.sacinfo.org.cn/',
    },
    {
        'key': 'MOA-AQUA-TG', 'name': '池塘养殖技术规范与水产养殖水质管理技术',
        'org': '农业农村部', 'doc_type': '行业标准与技术指导',
        'doc_no': '待核', 'url': 'http://www.moa.gov.cn/',
    },
    {
        'key': 'GD-FERT-GUIDE', 'name': '广东省主要农作物施肥指导意见',
        'org': '广东省农业农村厅', 'doc_type': '政府技术指导意见',
        'doc_no': '待核', 'url': 'http://dara.gd.gov.cn/',
    },
    {
        'key': 'CMA-AGRO', 'name': '农业气象旬报/月报与农事窗口',
        'org': '中国气象局 / 广东省气象局', 'doc_type': '农业气象服务',
        'doc_no': '待核', 'url': 'http://data.cma.cn/',
    },
    {
        'key': 'MOA-PEST-MON', 'name': '农作物病虫情报（病虫测报）',
        'org': '全国农业技术推广服务中心', 'doc_type': '病虫测报',
        'doc_no': '待核', 'url': 'http://www.natesc.org.cn/',
    },
    # ---- v3 新增：柑橘 / 香蕉。同样只登记**来源方向**，标准号一律「待核」。----
    {
        'key': 'GD-CITRUS-TG', 'name': '柑橘生产技术规程',
        'org': '广东省市场监督管理局', 'doc_type': '地方标准',
        'doc_no': '待核', 'url': 'https://dbba.sacinfo.org.cn/',
    },
    {
        'key': 'CARS-CITRUS', 'name': '柑橘栽培管理技术要点',
        'org': '农业农村部 国家柑橘产业技术体系', 'doc_type': '产业技术体系',
        'doc_no': '待核', 'url': 'http://www.moa.gov.cn/',
    },
    {
        'key': 'GD-BANANA-TG', 'name': '香蕉生产技术规程',
        'org': '广东省市场监督管理局', 'doc_type': '地方标准',
        'doc_no': '待核', 'url': 'https://dbba.sacinfo.org.cn/',
    },
    {
        'key': 'CARS-BANANA', 'name': '香蕉栽培管理技术要点',
        'org': '农业农村部 国家香蕉产业技术体系', 'doc_type': '产业技术体系',
        'doc_no': '待核', 'url': 'http://www.moa.gov.cn/',
    },
]

# 物候期（月粒度，支持跨年区间；待农学确认）
FARMING_PHENOPHASES = [
    {
        'product_id': 'lychee', 'name': '采后恢复期',
        'start_month': 7, 'end_month': 8,
        'color': '#4a8a6a', 'description': '恢复树势，培养健壮秋梢',
        'sort_order': 1,
    },
    {
        'product_id': 'lychee', 'name': '秋梢老熟期',
        'start_month': 9, 'end_month': 10,
        'color': '#1f5e43', 'description': '控梢促花，积累养分',
        'sort_order': 2,
    },
    {
        'product_id': 'lychee', 'name': '花芽分化期',
        'start_month': 11, 'end_month': 1,
        'color': '#4a6fa5', 'description': '控氮增磷钾，促进花芽分化',
        'sort_order': 3,
    },
    {
        'product_id': 'lychee', 'name': '花期',
        'start_month': 2, 'end_month': 3,
        'color': '#d9a227', 'description': '保花保果，花期忌施药',
        'sort_order': 4,
    },
    {
        'product_id': 'lychee', 'name': '果期',
        'start_month': 4, 'end_month': 6,
        'color': '#ef4444', 'description': '壮果、防蒂蛀虫、防裂果',
        'sort_order': 5,
    },
    {
        'product_id': 'longan', 'name': '采后恢复期',
        'start_month': 6, 'end_month': 7,
        'color': '#4a8a6a', 'description': '采后尽快施肥恢复树势',
        'sort_order': 1,
    },
    {
        'product_id': 'longan', 'name': '秋梢期',
        'start_month': 8, 'end_month': 9,
        'color': '#1f5e43', 'description': '统一放梢，控制冬梢',
        'sort_order': 2,
    },
    {
        'product_id': 'longan', 'name': '花芽分化期',
        'start_month': 10, 'end_month': 12,
        'color': '#4a6fa5', 'description': '控氮增磷钾，促进花芽分化',
        'sort_order': 3,
    },
    {
        'product_id': 'longan', 'name': '花期',
        'start_month': 1, 'end_month': 2,
        'color': '#d9a227', 'description': '疏花穗保花',
        'sort_order': 4,
    },
    {
        'product_id': 'longan', 'name': '果期',
        'start_month': 3, 'end_month': 5,
        'color': '#ef4444', 'description': '保果、壮果、适时采收',
        'sort_order': 5,
    },
    {
        'product_id': 'aquatic', 'name': '越冬期',
        'start_month': 12, 'end_month': 1,
        'color': '#4a6fa5', 'description': '保温防冻，减少投喂与操作',
        'sort_order': 1,
    },
    {
        'product_id': 'aquatic', 'name': '清塘放苗期',
        'start_month': 2, 'end_month': 3,
        'color': '#1f5e43', 'description': '清塘消毒、培水放苗',
        'sort_order': 2,
    },
    {
        'product_id': 'aquatic', 'name': '生长期',
        'start_month': 4, 'end_month': 6,
        'color': '#4a8a6a', 'description': '投喂与水质调控',
        'sort_order': 3,
    },
    {
        'product_id': 'aquatic', 'name': '育肥捕捞期',
        'start_month': 7, 'end_month': 9,
        'color': '#d9a227', 'description': '高温防缺氧，轮捕轮放',
        'sort_order': 4,
    },
    {
        'product_id': 'aquatic', 'name': '越冬准备期',
        'start_month': 10, 'end_month': 11,
        'color': '#ef4444', 'description': '干塘起捕，检修设备',
        'sort_order': 5,
    },
    {
        'product_id': 'rice', 'name': '冬闲期',
        'start_month': 12, 'end_month': 1,
        'color': '#4a6fa5', 'description': '翻耕晒田，杀灭越冬虫源',
        'sort_order': 1,
    },
    {
        'product_id': 'rice', 'name': '早稻生育期',
        'start_month': 2, 'end_month': 6,
        'color': '#1f5e43', 'description': '育秧、移栽、分蘖与晒田',
        'sort_order': 2,
    },
    {
        'product_id': 'rice', 'name': '晚稻生育期',
        'start_month': 7, 'end_month': 10,
        'color': '#4a8a6a', 'description': '穗肥、病虫害防治、灌浆收割',
        'sort_order': 3,
    },
    {
        'product_id': 'rice', 'name': '秋冬管理期',
        'start_month': 11, 'end_month': 11,
        'color': '#d9a227', 'description': '稻草还田，改良土壤',
        'sort_order': 4,
    },
    {
        'product_id': 'tea', 'name': '休眠越冬期',
        'start_month': 12, 'end_month': 1,
        'color': '#4a6fa5', 'description': '封园防冻，培土覆盖',
        'sort_order': 1,
    },
    {
        'product_id': 'tea', 'name': '春茶期',
        'start_month': 2, 'end_month': 4,
        'color': '#1f5e43', 'description': '催芽、采摘、春后修剪',
        'sort_order': 2,
    },
    {
        'product_id': 'tea', 'name': '夏茶期',
        'start_month': 5, 'end_month': 6,
        'color': '#4a8a6a', 'description': '遮阳降温，防治小绿叶蝉',
        'sort_order': 3,
    },
    {
        'product_id': 'tea', 'name': '秋茶期',
        'start_month': 7, 'end_month': 9,
        'color': '#d9a227', 'description': '秋茶采摘，施基肥',
        'sort_order': 4,
    },
    {
        'product_id': 'tea', 'name': '茶园管理期',
        'start_month': 10, 'end_month': 11,
        'color': '#ef4444', 'description': '清园深翻，防寒防冻',
        'sort_order': 5,
    },
    {
        'product_id': 'vegetable', 'name': '春茬期',
        'start_month': 2, 'end_month': 4,
        'color': '#1f5e43', 'description': '定植、搭架、病虫防治',
        'sort_order': 1,
    },
    {
        'product_id': 'vegetable', 'name': '夏茬期',
        'start_month': 5, 'end_month': 7,
        'color': '#4a8a6a', 'description': '遮阳降温，早晚灌溉',
        'sort_order': 2,
    },
    {
        'product_id': 'vegetable', 'name': '秋茬期',
        'start_month': 8, 'end_month': 10,
        'color': '#d9a227', 'description': '秋播定植，采收上市',
        'sort_order': 3,
    },
    {
        'product_id': 'vegetable', 'name': '越冬期',
        'start_month': 11, 'end_month': 1,
        'color': '#4a6fa5', 'description': '大棚保温，越冬管理',
        'sort_order': 4,
    },
    # ---- v3 新增：柑橘（广东以砂糖橘、贡柑、沙田柚、皇帝柑等为主）----
    # 物候期为月粒度参考值；广东柑橘采后至花芽分化间隔短，故把采后恢复并入花芽分化期前段。
    {
        'product_id': 'citrus', 'name': '花芽分化与越冬期',
        'start_month': 12, 'end_month': 1,
        'color': '#4a6fa5', 'description': '低温诱导花芽分化，防寒防冻',
        'sort_order': 1,
    },
    {
        'product_id': 'citrus', 'name': '现蕾开花期',
        'start_month': 2, 'end_month': 3,
        'color': '#1f5e43', 'description': '现蕾开花，保花授粉',
        'sort_order': 2,
    },
    {
        'product_id': 'citrus', 'name': '保果膨果期',
        'start_month': 4, 'end_month': 7,
        'color': '#4a8a6a', 'description': '控夏梢、保果、果实膨大',
        'sort_order': 3,
    },
    {
        'product_id': 'citrus', 'name': '秋梢抽发期',
        'start_month': 8, 'end_month': 10,
        'color': '#d9a227', 'description': '培养健壮秋梢（主要结果母枝）',
        'sort_order': 4,
    },
    {
        'product_id': 'citrus', 'name': '成熟采收期',
        'start_month': 11, 'end_month': 11,
        'color': '#ef4444', 'description': '果实成熟采收与采后恢复',
        'sort_order': 5,
    },
    # ---- v3 新增：香蕉（宿根蕉周年生长，抽蕾期随定植期浮动，此处按广东常见节律编排）----
    {
        'product_id': 'banana', 'name': '越冬与花芽分化期',
        'start_month': 12, 'end_month': 2,
        'color': '#4a6fa5', 'description': '防寒保温，花芽分化',
        'sort_order': 1,
    },
    {
        'product_id': 'banana', 'name': '春植与苗期管理',
        'start_month': 3, 'end_month': 4,
        'color': '#1f5e43', 'description': '春植定植，选留吸芽',
        'sort_order': 2,
    },
    {
        'product_id': 'banana', 'name': '营养生长期',
        'start_month': 5, 'end_month': 6,
        'color': '#4a8a6a', 'description': '追肥培土，壮大假茎',
        'sort_order': 3,
    },
    {
        'product_id': 'banana', 'name': '抽蕾与断蕾期',
        'start_month': 7, 'end_month': 9,
        'color': '#d9a227', 'description': '抽蕾断蕾，疏果防风',
        'sort_order': 4,
    },
    {
        'product_id': 'banana', 'name': '果实发育与采收期',
        'start_month': 10, 'end_month': 11,
        'color': '#ef4444', 'description': '果实发育、采收与防寒准备',
        'sort_order': 5,
    },
]

# 农事任务（年周期模板：task_md 为 MM-DD，逐年复现）
#   source_key -> FARMING_SOURCES（来源方向）
#   date_basis -> 该日期所依据的农艺逻辑（供农技人员复核与用户查看）
FARMING_TASKS = [
    {
        'product_id': 'lychee', 'phase': '花芽分化期',
        'title': '冬季清园', 'category': 'manage', 'priority': 'high',
        'task_md': '01-05', 'month': 1, 'icon': 'broom',
        'source_key': 'GD-LYCHEE-TG',
        'description': '清除落叶、病枝，集中烧毁，减少越冬病虫源',
        'tip': '清园后喷施3-5波美度石硫合剂，杀灭越冬病菌',
        'date_basis': '越冬病虫源进入休眠前完成清园效果最好。广东12月落叶尚未干净、2月花穗已萌动，宜在1月上旬动手。',
    },
    {
        'product_id': 'lychee', 'phase': '花芽分化期',
        'title': '树干涂白', 'category': 'manage', 'priority': 'medium',
        'task_md': '01-15', 'month': 1, 'icon': 'paint-roller',
        'source_key': 'GD-LYCHEE-TG',
        'description': '用石灰水涂白树干，防冻防虫',
        'tip': '涂白高度至第一主枝，石灰中可加入少量硫磺粉',
        'date_basis': '广东寒潮集中在1月中下旬，涂白须在降温前完成，兼防冻害与越冬害虫上树。',
    },
    {
        'product_id': 'lychee', 'phase': '花期',
        'title': '促花肥施用', 'category': 'fertilize', 'priority': 'high',
        'task_md': '02-10', 'month': 2, 'icon': 'seedling',
        'source_key': 'GD-FERT-GUIDE',
        'description': '施用速效磷钾肥，促进花芽分化',
        'tip': '每株施复合肥0.5-1公斤，配合有机肥效果更佳',
        'date_basis': '壮花肥应在花穗抽生前施下。过早易诱发冬梢、过晚来不及供应花穗发育；广东中南部花穗2月中下旬抽出。',
    },
    {
        'product_id': 'lychee', 'phase': '花期',
        'title': '花前病虫害预防', 'category': 'pest', 'priority': 'high',
        'task_md': '02-20', 'month': 2, 'icon': 'shield-virus',
        'source_key': 'MOA-PEST-MON',
        'description': '重点防治霜疫霉病、荔枝蝽蟓',
        'tip': '花前喷施一次杀菌剂+杀虫剂组合',
        'date_basis': '花穗抽出至开花前7–10天是霜疫霉病、荔枝蝽的防治窗口；花期忌用药，故必须前移。广东妃子笑始花约2月底。',
    },
    {
        'product_id': 'lychee', 'phase': '花期',
        'title': '花期管理', 'category': 'manage', 'priority': 'high',
        'task_md': '03-15', 'month': 3, 'icon': 'spa',
        'source_key': 'CARS-LZ',
        'description': '放蜂授粉，遇连续阴雨需人工辅助授粉',
        'tip': '花期忌喷农药，如需防治请在花前完成',
        'date_basis': '妃子笑3月中下旬盛花，蜂群须在盛花前3–5天引入才能赶上授粉高峰；花期严禁喷药。',
    },
    {
        'product_id': 'lychee', 'phase': '花期',
        'title': '保花保果', 'category': 'fertilize', 'priority': 'medium',
        'task_md': '03-28', 'month': 3, 'icon': 'hand-holding-heart',
        'source_key': 'CARS-LZ',
        'description': '喷施磷酸二氢钾+硼肥，提高坐果率',
        'tip': '浓度0.2%磷酸二氢钾+0.1%硼砂，花期喷2次',
        'date_basis': '谢花后即进入第一次生理落果，保果须在谢花后3–7天内完成，过晚效果显著下降。',
    },
    {
        'product_id': 'lychee', 'phase': '果期',
        'title': '蒂蛀虫防治', 'category': 'pest', 'priority': 'high',
        'task_md': '04-18', 'month': 4, 'icon': 'bug',
        'source_key': 'MOA-PEST-MON',
        'description': '果实发育期重点防治蒂蛀虫',
        'tip': '成虫羽化高峰期喷药，选用高效氯氰菊酯',
        'date_basis': '第一代蒂蛀虫成虫羽化高峰在4月中下旬幼果期，此时施药防效最佳；错过则幼虫已蛀入果内。',
    },
    {
        'product_id': 'lychee', 'phase': '果期',
        'title': '果实膨大期', 'category': 'fertilize', 'priority': 'high',
        'task_md': '04-25', 'month': 4, 'icon': 'apple-alt',
        'source_key': 'GD-FERT-GUIDE',
        'description': '施壮果肥，保持充足水分供应',
        'tip': '每株施硫酸钾0.5公斤，配合灌水',
        'date_basis': '第二次生理落果结束前后施壮果肥。过早施氮易加剧落果，过晚影响果实膨大。',
    },
    {
        'product_id': 'lychee', 'phase': '果期',
        'title': '果实转色管理', 'category': 'manage', 'priority': 'medium',
        'task_md': '05-25', 'month': 5, 'icon': 'palette',
        'source_key': 'CARS-LZ',
        'description': '控制氮肥，增施钾肥促进着色',
        'tip': '转色期减少灌水，提高果实甜度',
        'date_basis': '早熟品种5月下旬开始转色，控氮增钾须在转色初期启动；转色后减水可提高糖度。',
    },
    {
        'product_id': 'lychee', 'phase': '果期',
        'title': '排水防裂果', 'category': 'water', 'priority': 'high',
        'task_md': None, 'month': 5, 'icon': 'tint',
        'source_key': 'CARS-LZ',
        'description': '果实成熟期遇暴雨易裂果，注意排水',
        'tip': '雨后及时排水，可覆盖地膜减少水分波动',
        'date_basis': '雨水管理为持续性作业：果实成熟期土壤水分剧烈波动即裂果，需在整个成熟期保持排水通畅，故不指定单一日期。',
    },
    {
        'product_id': 'lychee', 'phase': '果期',
        'title': '荔枝采收', 'category': 'harvest', 'priority': 'high',
        'task_md': '06-10', 'month': 6, 'icon': 'shopping-basket',
        'source_key': 'GD-LYCHEE-TG',
        'description': '适时采收成熟果实，分批采摘',
        'tip': '果皮转红2/3时采收，保留果穗枝保证品质',
        'date_basis': '以早熟主栽品种妃子笑为基准，果皮转红2/3时6月上中旬采收；桂味、糯米糍顺延至6月下旬。',
    },
    {
        'product_id': 'lychee', 'phase': '果期',
        'title': '采后修剪', 'category': 'manage', 'priority': 'high',
        'task_md': '06-15', 'month': 6, 'icon': 'cut',
        'source_key': 'CARS-LZ',
        'description': '采果后进行回缩修剪，保持树冠通风',
        'tip': '修剪量不超过树冠的1/3，保留内膛枝',
        'date_basis': '采果后立即回缩修剪。越早越能保证末次秋梢在11月前如期老熟，直接决定次年成花。',
    },
    {
        'product_id': 'lychee', 'phase': '采后恢复期',
        'title': '施用恢复肥', 'category': 'fertilize', 'priority': 'high',
        'task_md': '07-05', 'month': 7, 'icon': 'fill-drip',
        'source_key': 'GD-FERT-GUIDE',
        'description': '采果后重施有机肥，恢复树势',
        'tip': '每株施有机肥10-20公斤+复合肥1公斤',
        'date_basis': '采后15天内重施有机肥+复合肥恢复树势。过晚将拖累第一次秋梢的质量。',
    },
    {
        'product_id': 'lychee', 'phase': '采后恢复期',
        'title': '秋梢管理', 'category': 'manage', 'priority': 'medium',
        'task_md': '07-20', 'month': 7, 'icon': 'tree',
        'source_key': 'CARS-LZ',
        'description': '培养健壮秋梢，为来年结果打基础',
        'tip': '统一放梢，抹除零星早发的芽',
        'date_basis': '第一次秋梢7月中下旬萌发，放梢前须抹除零星早发芽，保证放梢整齐便于后续统一控梢。',
    },
    {
        'product_id': 'lychee', 'phase': '采后恢复期',
        'title': '秋梢病虫防治', 'category': 'pest', 'priority': 'medium',
        'task_md': '08-10', 'month': 8, 'icon': 'shield-virus',
        'source_key': 'MOA-PEST-MON',
        'description': '保护新梢，防治尺蠖、卷叶蛾',
        'tip': '新梢萌发1-2厘米时喷第一次药',
        'date_basis': '第二次（结果母枝）秋梢8月中下旬抽出，尺蠖、卷叶蛾在新梢长1–2cm时开始危害，须此时首次用药。',
    },
    {
        'product_id': 'lychee', 'phase': '采后恢复期',
        'title': '水分管理', 'category': 'water', 'priority': 'medium',
        'task_md': None, 'month': 8, 'icon': 'tint',
        'source_key': 'CARS-LZ',
        'description': '秋梢生长期保持充足水分',
        'tip': '干旱时及时灌水，每7-10天一次',
        'date_basis': '水分管理为持续性作业：秋梢生长期需保持土壤湿润以利抽梢与老熟，无法落到单一日期。',
    },
    {
        'product_id': 'lychee', 'phase': '秋梢老熟期',
        'title': '深翻改土', 'category': 'manage', 'priority': 'low',
        'task_md': '09-20', 'month': 9, 'icon': 'mountain',
        'source_key': 'GD-LYCHEE-TG',
        'description': '结合施有机肥进行深翻改土',
        'tip': '深翻30-40厘米，断根促发新根',
        'date_basis': '第一次秋梢老熟、末次秋梢尚未抽出的间隙期深翻改土，避开新梢生长期以免伤根影响放梢。',
    },
    {
        'product_id': 'lychee', 'phase': '秋梢老熟期',
        'title': '冬季清园准备', 'category': 'manage', 'priority': 'low',
        'task_md': '10-20', 'month': 10, 'icon': 'broom',
        'source_key': 'GD-LYCHEE-TG',
        'description': '清理果园杂草，准备冬季管理',
        'tip': '清除园内杂草和落叶，减少病虫越冬场所',
        'date_basis': '入冬前清除园内杂草落叶，压减越冬病虫基数，为12月全面清园打基础。',
    },
    {
        'product_id': 'lychee', 'phase': '秋梢老熟期',
        'title': '花芽分化期', 'category': 'fertilize', 'priority': 'high',
        'task_md': '10-25', 'month': 10, 'icon': 'seedling',
        'source_key': 'GD-FERT-GUIDE',
        'description': '控制氮肥，增施磷钾肥促进花芽分化',
        'tip': '叶面喷施0.3%磷酸二氢钾',
        'date_basis': '末次秋梢老熟后开始控氮、增施磷钾诱导花芽分化，广东花芽生理分化自10月下旬启动。',
    },
    {
        'product_id': 'lychee', 'phase': '花芽分化期',
        'title': '控梢促花', 'category': 'manage', 'priority': 'high',
        'task_md': '11-10', 'month': 11, 'icon': 'hand-paper',
        'source_key': 'CARS-LZ',
        'description': '末次秋梢老熟后开始控梢',
        'tip': '可采用环割或喷施控梢药剂',
        'date_basis': '控梢促花须在末次秋梢完全老熟后进行：此时枝条已停止伸长，抑制其抽发冬梢才能把养分转向花芽分化。广东中南部末次秋梢多在10月下旬至11月上旬老熟，故控梢安排在11月上中旬。',
    },
    {
        'product_id': 'lychee', 'phase': '花芽分化期',
        'title': '冬季修剪', 'category': 'manage', 'priority': 'medium',
        'task_md': '11-20', 'month': 11, 'icon': 'cut',
        'source_key': 'GD-LYCHEE-TG',
        'description': '疏除过密枝、交叉枝、病虫枝',
        'tip': '修剪后涂抹伤口愈合剂',
        'date_basis': '控梢促花完成后修剪，疏除过密枝、交叉枝、病虫枝，改善通风透光而不刺激新梢。',
    },
    {
        'product_id': 'lychee', 'phase': '花芽分化期',
        'title': '防寒措施', 'category': 'manage', 'priority': 'medium',
        'task_md': '11-25', 'month': 11, 'icon': 'snowflake',
        'source_key': 'CMA-AGRO',
        'description': '幼树覆盖防寒，树盘覆草',
        'tip': '低温来临前树冠覆盖薄膜',
        'date_basis': '广东寒潮始于12月，幼树覆盖与树盘覆草须在12月上旬前完成，故在11月下旬部署。',
    },
    {
        'product_id': 'lychee', 'phase': '花芽分化期',
        'title': '施基肥', 'category': 'fertilize', 'priority': 'medium',
        'task_md': '12-10', 'month': 12, 'icon': 'fill-drip',
        'source_key': 'GD-FERT-GUIDE',
        'description': '深施有机肥改良土壤',
        'tip': '沿树冠滴水线开沟施肥，深度30-40厘米',
        'date_basis': '冬季沿滴水线开沟深施有机肥改良土壤；先于清园施药，避免作业相互干扰。',
    },
    {
        'product_id': 'lychee', 'phase': '花芽分化期',
        'title': '冬季清园', 'category': 'manage', 'priority': 'high',
        'task_md': '12-20', 'month': 12, 'icon': 'broom',
        'source_key': 'GD-LYCHEE-TG',
        'description': '全面清园，喷施石硫合剂',
        'tip': '落叶后全园喷施3-5波美度石硫合剂',
        'date_basis': '落叶后全园喷3–5波美度石硫合剂。此时越冬病虫抗性最低，是全年清园效果最好的一次。',
    },
    {
        'product_id': 'longan', 'phase': '花期',
        'title': '冬季管理', 'category': 'manage', 'priority': 'medium',
        'task_md': '01-10', 'month': 1, 'icon': 'snowflake',
        'source_key': 'GD-LONGAN-TG',
        'description': '清园修剪，防寒防冻',
        'tip': '喷施石硫合剂清园',
        'date_basis': '龙眼耐寒性弱于荔枝，清园修剪与防寒须在1月上旬低温来临前完成。',
    },
    {
        'product_id': 'longan', 'phase': '花期',
        'title': '促花肥', 'category': 'fertilize', 'priority': 'high',
        'task_md': '02-15', 'month': 2, 'icon': 'seedling',
        'source_key': 'GD-FERT-GUIDE',
        'description': '施磷钾肥促花',
        'tip': '每株施复合肥0.5公斤',
        'date_basis': '花穗抽生前施磷钾肥促花。龙眼抽穗略晚于荔枝，广东约2月中下旬，过早易发冬梢。',
    },
    {
        'product_id': 'longan', 'phase': '果期',
        'title': '花穗管理', 'category': 'manage', 'priority': 'high',
        'task_md': '03-25', 'month': 3, 'icon': 'spa',
        'source_key': 'CARS-LZ',
        'description': '疏花穗，去除弱花',
        'tip': '保留60-70%花穗',
        'date_basis': '花穗抽出后疏除弱穗、病穗并保留60–70%；广东龙眼盛花在4月上中旬，须在盛花前完成疏穗。',
    },
    {
        'product_id': 'longan', 'phase': '果期',
        'title': '保果措施', 'category': 'fertilize', 'priority': 'high',
        'task_md': '04-20', 'month': 4, 'icon': 'hand-holding-heart',
        'source_key': 'CARS-LZ',
        'description': '喷施保果药剂',
        'tip': '谢花后喷九二零+磷酸二氢钾',
        'date_basis': '谢花后即喷赤霉素+磷酸二氢钾保果，须在谢花后3–7天内完成，过晚落果已定。',
    },
    {
        'product_id': 'longan', 'phase': '果期',
        'title': '果实膨大', 'category': 'fertilize', 'priority': 'high',
        'task_md': '05-20', 'month': 5, 'icon': 'apple-alt',
        'source_key': 'GD-FERT-GUIDE',
        'description': '加强水肥管理',
        'tip': '施壮果肥，保持水分',
        'date_basis': '第二次生理落果后施壮果肥并保持土壤湿润；此期缺水直接导致果实偏小。',
    },
    {
        'product_id': 'longan', 'phase': '采后恢复期',
        'title': '龙眼采收', 'category': 'harvest', 'priority': 'high',
        'task_md': '06-25', 'month': 6, 'icon': 'shopping-basket',
        'source_key': 'GD-LONGAN-TG',
        'description': '适时采收',
        'tip': '果壳转黄、果肉饱满时采收',
        'date_basis': '以早熟品种（如古山二号）为基准6月下旬采收；石硖顺延至7月中下旬、储良至8月中下旬。',
    },
    {
        'product_id': 'longan', 'phase': '采后恢复期',
        'title': '采后管理', 'category': 'manage', 'priority': 'high',
        'task_md': '07-10', 'month': 7, 'icon': 'cut',
        'source_key': 'CARS-LZ',
        'description': '修剪+施恢复肥',
        'tip': '采后尽快施肥恢复树势',
        'date_basis': '采后立即修剪并施恢复肥。早熟种6月底采完，7月上旬为最佳恢复窗口。',
    },
    {
        'product_id': 'longan', 'phase': '秋梢期',
        'title': '秋梢管理', 'category': 'manage', 'priority': 'medium',
        'task_md': '08-20', 'month': 8, 'icon': 'tree',
        'source_key': 'CARS-LZ',
        'description': '培养健壮秋梢',
        'tip': '统一放梢，防治新梢害虫',
        'date_basis': '龙眼结果母枝为9–10月抽出的秋梢，8月下旬放梢可使其在11月前老熟并防治新梢害虫。',
    },
    {
        'product_id': 'longan', 'phase': '秋梢期',
        'title': '控梢', 'category': 'manage', 'priority': 'high',
        'task_md': '09-28', 'month': 9, 'icon': 'hand-paper',
        'source_key': 'CARS-LZ',
        'description': '控制冬梢萌发',
        'tip': '环割或喷控梢药剂',
        'date_basis': '末次秋梢抽出整齐后疏除零星晚秋梢与早发冬梢，促使秋梢统一老熟；冬梢的全面控制随后于11月进行。',
    },
    {
        'product_id': 'longan', 'phase': '花芽分化期',
        'title': '花芽分化', 'category': 'fertilize', 'priority': 'medium',
        'task_md': '10-25', 'month': 10, 'icon': 'seedling',
        'source_key': 'GD-FERT-GUIDE',
        'description': '促进花芽分化',
        'tip': '控氮增磷钾',
        'date_basis': '控氮增磷钾诱导花芽分化。广东龙眼花芽生理分化自10月下旬启动，与末次秋梢老熟同步。',
    },
    {
        'product_id': 'longan', 'phase': '花芽分化期',
        'title': '冬季修剪', 'category': 'manage', 'priority': 'medium',
        'task_md': '11-20', 'month': 11, 'icon': 'cut',
        'source_key': 'GD-LONGAN-TG',
        'description': '修剪整形',
        'tip': '疏除密枝病枝',
        'date_basis': '末次秋梢老熟后修剪整形，疏除密枝病枝，改善通风透光且不刺激冬梢。',
    },
    {
        'product_id': 'longan', 'phase': '花芽分化期',
        'title': '清园施肥', 'category': 'manage', 'priority': 'high',
        'task_md': '12-15', 'month': 12, 'icon': 'broom',
        'source_key': 'GD-LONGAN-TG',
        'description': '冬季清园+施基肥',
        'tip': '有机肥深施改土',
        'date_basis': '冬季清园与有机肥深施改土同步进行；12月中旬前完成可避开寒潮作业。',
    },
    {
        'product_id': 'aquatic', 'phase': '越冬期',
        'title': '越冬管理', 'category': 'manage', 'priority': 'high',
        'task_md': '01-10', 'month': 1, 'icon': 'snowflake',
        'source_key': 'MOA-AQUA-TG',
        'description': '保持水温，减少投喂',
        'tip': '加深水位至2米以上保温',
        'date_basis': '广东1月为全年最低温时段，水深须在寒潮到来前加深至2m以上并减少操作。',
    },
    {
        'product_id': 'aquatic', 'phase': '清塘放苗期',
        'title': '清塘消毒', 'category': 'manage', 'priority': 'high',
        'task_md': '02-25', 'month': 2, 'icon': 'broom',
        'source_key': 'MOA-AQUA-TG',
        'description': '干塘暴晒，生石灰消毒',
        'tip': '每亩用生石灰75-100公斤',
        'date_basis': '干塘暴晒与生石灰消毒须在放苗前20–30天完成，按3月下旬放苗倒推为2月下旬。',
    },
    {
        'product_id': 'aquatic', 'phase': '清塘放苗期',
        'title': '放苗准备', 'category': 'manage', 'priority': 'high',
        'task_md': '03-10', 'month': 3, 'icon': 'fish',
        'source_key': 'MOA-AQUA-TG',
        'description': '培水、试水、放苗',
        'tip': '水温稳定15℃以上再放苗',
        'date_basis': '生石灰消毒后需7–10天药性消失、再培水7天，故3月上中旬试水、3月下旬放苗（水温稳定15℃以上）。',
    },
    {
        'product_id': 'aquatic', 'phase': '生长期',
        'title': '水霉病预防', 'category': 'pest', 'priority': 'high',
        'task_md': '04-10', 'month': 4, 'icon': 'shield-virus',
        'source_key': 'MOA-PEST-MON',
        'description': '放苗后预防水霉病与寄生虫',
        'tip': '避免拉网损伤，必要时泼洒食盐水或碘制剂',
        'date_basis': '水霉病在15–20℃最易流行：4月水温正处该区间，且鱼体刚经历拉网、放苗损伤，是预防关键窗口；5月后水温升高、发病率明显下降。',
    },
    {
        'product_id': 'aquatic', 'phase': '生长期',
        'title': '水质调控', 'category': 'water', 'priority': 'high',
        'task_md': None, 'month': 4, 'icon': 'tint',
        'source_key': 'MOA-AQUA-TG',
        'description': '保持水质稳定',
        'tip': '每7-10天换水一次，每次换1/3',
        'date_basis': '水质调控为持续性作业：需按周期换水并监测溶氧、氨氮，无法落到单一日期。',
    },
    {
        'product_id': 'aquatic', 'phase': '生长期',
        'title': '投喂管理', 'category': 'manage', 'priority': 'medium',
        'task_md': '05-10', 'month': 5, 'icon': 'utensils',
        'source_key': 'MOA-AQUA-TG',
        'description': '根据天气调整投喂量',
        'tip': '阴雨天减量或停喂',
        'date_basis': '水温回升至25℃左右进入摄食旺盛期，广东5月上旬起按天气与摄食情况逐日调整投喂量。',
    },
    {
        'product_id': 'aquatic', 'phase': '生长期',
        'title': '增氧设备检修', 'category': 'manage', 'priority': 'high',
        'task_md': '06-15', 'month': 6, 'icon': 'tools',
        'source_key': 'MOA-AQUA-TG',
        'description': '检修增氧机、水泵与供电线路并试运行',
        'tip': '备好应急增氧剂，检查防逃设施',
        'date_basis': '广东6月中下旬起进入高温闷热期，夜间泛塘风险陡增；增氧设备须在高温到来前完成检修试运行，晚于6月下旬一旦故障将直接造成死鱼。',
    },
    {
        'product_id': 'aquatic', 'phase': '生长期',
        'title': '高温防缺氧', 'category': 'water', 'priority': 'high',
        'task_md': None, 'month': 6, 'icon': 'temperature-high',
        'source_key': 'MOA-AQUA-TG',
        'description': '开启增氧机，预防泛塘',
        'tip': '中午和凌晨各开增氧机2-3小时',
        'date_basis': '增氧为持续性作业：高温期须每日中午与凌晨定时开机，无固定单一日期。',
    },
    {
        'product_id': 'aquatic', 'phase': '育肥捕捞期',
        'title': '病害高发防控', 'category': 'pest', 'priority': 'high',
        'task_md': '07-10', 'month': 7, 'icon': 'shield-virus',
        'source_key': 'MOA-PEST-MON',
        'description': '高温期病害频发',
        'tip': '定期消毒，拌喂大蒜素预防',
        'date_basis': '7–8月水温最高、病害进入高发期，须提前开展水体消毒与内服预防，而非发病后补救。',
    },
    {
        'product_id': 'aquatic', 'phase': '育肥捕捞期',
        'title': '轮捕轮放', 'category': 'harvest', 'priority': 'medium',
        'task_md': '08-15', 'month': 8, 'icon': 'fishing',
        'source_key': 'MOA-AQUA-TG',
        'description': '达到规格的及时捕捞',
        'tip': '降低密度有利于剩余个体生长',
        'date_basis': '达到商品规格即及时轮捕，降低密度有利于剩余个体生长；8月中旬为第一个集中出塘节点。',
    },
    {
        'product_id': 'aquatic', 'phase': '育肥捕捞期',
        'title': '秋季管理', 'category': 'manage', 'priority': 'medium',
        'task_md': '09-20', 'month': 9, 'icon': 'leaf',
        'source_key': 'MOA-AQUA-TG',
        'description': '调整投喂，预防秋瘟',
        'tip': '水温下降时逐步减少投喂量',
        'date_basis': '9月下旬水温开始下降，逐步减料并预防「秋瘟」；此时是全年第二个病害风险窗口。',
    },
    {
        'product_id': 'aquatic', 'phase': '越冬准备期',
        'title': '越冬准备', 'category': 'manage', 'priority': 'high',
        'task_md': '10-20', 'month': 10, 'icon': 'snowflake',
        'source_key': 'MOA-AQUA-TG',
        'description': '加深水位，减少操作',
        'tip': '达到商品规格的抓紧起捕上市',
        'date_basis': '10月下旬起加深水位、减少拉网等机械损伤，为越冬做准备；达规格的抓紧起捕上市。',
    },
    {
        'product_id': 'aquatic', 'phase': '越冬准备期',
        'title': '干塘起捕', 'category': 'harvest', 'priority': 'high',
        'task_md': '11-20', 'month': 11, 'icon': 'fishing',
        'source_key': 'MOA-AQUA-TG',
        'description': '年底干塘起捕',
        'tip': '捕后清塘消毒准备来年',
        'date_basis': '年底干塘起捕并清整池塘，11月中下旬完成可留出时间晒塘和检修。',
    },
    {
        'product_id': 'aquatic', 'phase': '越冬期',
        'title': '设备维护', 'category': 'manage', 'priority': 'low',
        'task_md': '12-15', 'month': 12, 'icon': 'tools',
        'source_key': 'MOA-AQUA-TG',
        'description': '维修增氧机、投饲机',
        'tip': '利用空闲期检修养殖设备',
        'date_basis': '利用非生产期检修增氧机、投饲机，为次年生产做准备。',
    },
    {
        'product_id': 'rice', 'phase': '冬闲期',
        'title': '冬闲田管理', 'category': 'manage', 'priority': 'low',
        'task_md': '01-10', 'month': 1, 'icon': 'mountain',
        'source_key': 'MOA-RICE-TG',
        'description': '翻耕冬闲田，晒田风化',
        'tip': '深翻20-25厘米，利用低温杀灭越冬虫源',
        'date_basis': '冬闲田翻耕晒垡宜在1月上旬完成，冻融风化杀灭越冬虫源的效果最好。',
    },
    {
        'product_id': 'rice', 'phase': '早稻生育期',
        'title': '浸种催芽', 'category': 'manage', 'priority': 'high',
        'task_md': '02-20', 'month': 2, 'icon': 'seedling',
        'source_key': 'MOA-RICE-TG',
        'description': '早稻浸种催芽',
        'tip': '温水浸种48小时，保持30-35℃催芽',
        'date_basis': '早稻按3月上旬播种倒推，广东粤中宜2月下旬浸种催芽；粤西可提前至2月中旬。',
    },
    {
        'product_id': 'rice', 'phase': '早稻生育期',
        'title': '播种育秧', 'category': 'manage', 'priority': 'high',
        'task_md': '03-10', 'month': 3, 'icon': 'seedling',
        'source_key': 'CMA-AGRO',
        'description': '适时播种，培育壮秧',
        'tip': '秧田施足基肥，控制播种量',
        'date_basis': '秧龄25–30天，按4月上中旬移栽倒推；且须日平均气温稳定通过12℃方可播种。',
    },
    {
        'product_id': 'rice', 'phase': '早稻生育期',
        'title': '移栽', 'category': 'manage', 'priority': 'high',
        'task_md': '04-10', 'month': 4, 'icon': 'exchange-alt',
        'source_key': 'MOA-RICE-TG',
        'description': '适时移栽，合理密植',
        'tip': '株行距20×25厘米，每穴2-3苗',
        'date_basis': '广东早稻粤中4月上中旬抛秧移栽，秧龄25–30天，避过早春低温与后期高温逼熟。',
    },
    {
        'product_id': 'rice', 'phase': '早稻生育期',
        'title': '分蘖期管理', 'category': 'fertilize', 'priority': 'high',
        'task_md': '05-05', 'month': 5, 'icon': 'tree',
        'source_key': 'GD-FERT-GUIDE',
        'description': '追施分蘖肥，促进早发',
        'tip': '移栽后7-10天追施尿素10公斤/亩',
        'date_basis': '移栽后7–10天追施分蘖肥，对应5月上旬；过迟会诱发无效分蘖、加重病害。',
    },
    {
        'product_id': 'rice', 'phase': '早稻生育期',
        'title': '晒田控苗', 'category': 'water', 'priority': 'high',
        'task_md': '06-05', 'month': 6, 'icon': 'sun',
        'source_key': 'MOA-RICE-TG',
        'description': '排水晒田，控制无效分蘖',
        'tip': '田面出现鸡爪裂时复水',
        'date_basis': '晒田须在够苗后至分蘖末期进行：此时晒田可抑制无效分蘖、促进根系下扎，过晚则穗数已定、作用有限。广东早稻6月上旬达到够苗，故晒田窗口落在6月上中旬。',
    },
    {
        'product_id': 'rice', 'phase': '晚稻生育期',
        'title': '晚稻播种育秧', 'category': 'manage', 'priority': 'high',
        'task_md': '07-10', 'month': 7, 'icon': 'seedling',
        'source_key': 'MOA-RICE-TG',
        'description': '晚稻适时播种，培育适龄壮秧',
        'tip': '广东粤中7月上中旬播种，秧龄20-25天，注意遮阳防高温烧苗',
        'date_basis': '晚稻秧龄20–25天，按8月上旬移栽倒推；过早秧龄过长易老化、过晚影响安全齐穗。（原任务集缺少晚稻起点，本次补入）',
    },
    {
        'product_id': 'rice', 'phase': '晚稻生育期',
        'title': '稻飞虱防治', 'category': 'pest', 'priority': 'high',
        'task_md': '08-10', 'month': 8, 'icon': 'bug',
        'source_key': 'MOA-PEST-MON',
        'description': '重点防治稻飞虱、纹枯病',
        'tip': '选用吡蚜酮+井冈霉素组合',
        'date_basis': '晚稻8月进入分蘖至拔节期，稻飞虱与纹枯病开始上升，须在虫量激增前防治。',
    },
    {
        'product_id': 'rice', 'phase': '晚稻生育期',
        'title': '穗肥施用', 'category': 'fertilize', 'priority': 'high',
        'task_md': '09-05', 'month': 9, 'icon': 'fill-drip',
        'source_key': 'GD-FERT-GUIDE',
        'description': '幼穗分化期施穗肥',
        'tip': '每亩施复合肥5-8公斤',
        'date_basis': '穗肥须在幼穗分化期施用，此时施肥对增加穗粒数与粒重最有效，过早易造成无效分蘖、过晚则颖花已定。广东晚稻幼穗分化期为8月下旬至9月上旬，故穗肥安排在9月上旬。',
    },
    {
        'product_id': 'rice', 'phase': '晚稻生育期',
        'title': '抽穗扬花', 'category': 'manage', 'priority': 'medium',
        'task_md': '09-25', 'month': 9, 'icon': 'spa',
        'source_key': 'MOA-RICE-TG',
        'description': '保持浅水层，遇寒露风灌深水保温',
        'tip': '喷施磷酸二氢钾提高结实率',
        'date_basis': '晚稻抽穗扬花期须保持浅水层；广东9月下旬至10月上旬抽穗，遇寒露风灌深水保温。',
    },
    {
        'product_id': 'rice', 'phase': '晚稻生育期',
        'title': '灌浆期叶面施肥', 'category': 'fertilize', 'priority': 'medium',
        'task_md': '10-05', 'month': 10, 'icon': 'spray-can',
        'source_key': 'GD-FERT-GUIDE',
        'description': '叶面喷施磷酸二氢钾，防止功能叶早衰',
        'tip': '0.2%磷酸二氢钾连喷2次，间隔7天',
        'date_basis': '晚稻齐穗后至灌浆初期叶面追施磷钾，可延缓功能叶早衰、提高结实率与千粒重；10月下旬进入蜡熟后喷施已无实际意义。',
    },
    {
        'product_id': 'rice', 'phase': '晚稻生育期',
        'title': '灌浆结实', 'category': 'water', 'priority': 'medium',
        'task_md': None, 'month': 10, 'icon': 'apple-alt',
        'source_key': 'MOA-RICE-TG',
        'description': '干湿交替灌溉',
        'tip': '收割前7天断水，便于机收',
        'date_basis': '灌溉管理为持续性作业：灌浆期需反复干湿交替，收割前7天断水，无固定单一日期。',
    },
    {
        'product_id': 'rice', 'phase': '秋冬管理期',
        'title': '晚稻收割', 'category': 'harvest', 'priority': 'high',
        'task_md': '11-08', 'month': 11, 'icon': 'shopping-basket',
        'source_key': 'MOA-RICE-TG',
        'description': '适时收割晚稻',
        'tip': '九成黄时收割，减少落粒损失',
        'date_basis': '广东晚稻粤中11月上旬收获，九成黄时收割可减少落粒损失。',
    },
    {
        'product_id': 'rice', 'phase': '冬闲期',
        'title': '稻草还田', 'category': 'manage', 'priority': 'low',
        'task_md': '12-10', 'month': 12, 'icon': 'recycle',
        'source_key': 'MOA-RICE-TG',
        'description': '稻草粉碎还田改良土壤',
        'tip': '配合施氮肥加速分解',
        'date_basis': '收割后稻草粉碎还田并配施氮肥加速分解，12月中旬前完成有利于冬闲期腐熟。',
    },
    {
        'product_id': 'tea', 'phase': '休眠越冬期',
        'title': '冬季封园', 'category': 'manage', 'priority': 'high',
        'task_md': '01-10', 'month': 1, 'icon': 'snowflake',
        'source_key': 'GD-TEA-TG',
        'description': '喷施石硫合剂封园',
        'tip': '全园喷施0.5波美度石硫合剂',
        'date_basis': '封园宜在越冬期开始前完成；石硫合剂在休眠期使用对茶树安全，萌芽后则易产生药害。',
    },
    {
        'product_id': 'tea', 'phase': '春茶期',
        'title': '施催芽肥', 'category': 'fertilize', 'priority': 'high',
        'task_md': '02-10', 'month': 2, 'icon': 'seedling',
        'source_key': 'GD-FERT-GUIDE',
        'description': '施速效氮肥催芽',
        'tip': '每亩施尿素15-20公斤',
        'date_basis': '催芽肥须在春茶开采前30–40天施下，广东单丛/红茶区约2月上中旬。',
    },
    {
        'product_id': 'tea', 'phase': '春茶期',
        'title': '春茶准备', 'category': 'manage', 'priority': 'medium',
        'task_md': '03-05', 'month': 3, 'icon': 'mug-hot',
        'source_key': 'GD-TEA-TG',
        'description': '检修制茶设备，准备采摘',
        'tip': '提前联系采茶工，春茶季用工紧张',
        'date_basis': '设备检修与采工组织须早于开采期完成；广东凤凰单丛最早3月下旬开采，春茶季用工极紧张。',
    },
    {
        'product_id': 'tea', 'phase': '春茶期',
        'title': '春茶采摘', 'category': 'harvest', 'priority': 'high',
        'task_md': '04-05', 'month': 4, 'icon': 'hand-paper',
        'source_key': 'GD-TEA-TG',
        'description': '采摘一芽一叶或一芽二叶',
        'tip': '晴天上午露水干后采摘品质最佳',
        'date_basis': '清明前后是广东春茶开采主峰，按一芽一叶或一芽二叶标准采摘，品质最佳。',
    },
    {
        'product_id': 'tea', 'phase': '夏茶期',
        'title': '茶园修剪', 'category': 'manage', 'priority': 'medium',
        'task_md': '05-10', 'month': 5, 'icon': 'cut',
        'source_key': 'GD-TEA-TG',
        'description': '春茶后轻修剪',
        'tip': '剪去3-5厘米，促进夏芽萌发',
        'date_basis': '春茶结束后轻修剪（剪去3–5cm），广东约5月上中旬，剪后促发夏芽。',
    },
    {
        'product_id': 'tea', 'phase': '夏茶期',
        'title': '夏茶管理', 'category': 'manage', 'priority': 'medium',
        'task_md': '06-10', 'month': 6, 'icon': 'temperature-high',
        'source_key': 'MOA-PEST-MON',
        'description': '遮阳降温，防治虫害',
        'tip': '覆盖遮阳网减少高温灼伤',
        'date_basis': '6月起高温强光，须在盛夏前覆盖遮阳网降温，并防治小绿叶蝉第一代虫峰。',
    },
    {
        'product_id': 'tea', 'phase': '秋茶期',
        'title': '小绿叶蝉防治', 'category': 'pest', 'priority': 'high',
        'task_md': '07-10', 'month': 7, 'icon': 'bug',
        'source_key': 'MOA-PEST-MON',
        'description': '防治茶小绿叶蝉',
        'tip': '黄板诱杀+生物农药防治',
        'date_basis': '7–8月为小绿叶蝉虫口高峰期，防治适期在若虫盛期，宜黄板诱杀配合生物农药。',
    },
    {
        'product_id': 'tea', 'phase': '秋茶期',
        'title': '秋茶采摘', 'category': 'harvest', 'priority': 'medium',
        'task_md': '08-25', 'month': 8, 'icon': 'hand-paper',
        'source_key': 'GD-TEA-TG',
        'description': '采摘秋茶',
        'tip': '秋茶香气好，可制作高香型茶',
        'date_basis': '广东秋茶8月下旬开采；秋茶香气物质积累多，宜制作高香型茶。',
    },
    {
        'product_id': 'tea', 'phase': '秋茶期',
        'title': '施基肥', 'category': 'fertilize', 'priority': 'high',
        'task_md': '09-25', 'month': 9, 'icon': 'fill-drip',
        'source_key': 'GD-FERT-GUIDE',
        'description': '重施有机基肥',
        'tip': '沿树冠滴水线开沟深施',
        'date_basis': '秋茶采摘结束后开沟深施有机基肥。广东9月下旬气温尚高、根系仍活跃，利于越冬前吸收。',
    },
    {
        'product_id': 'tea', 'phase': '茶园管理期',
        'title': '秋季修剪', 'category': 'manage', 'priority': 'medium',
        'task_md': '10-20', 'month': 10, 'icon': 'cut',
        'source_key': 'GD-TEA-TG',
        'description': '茶树深修剪或重修剪',
        'tip': '衰老茶树可重度修剪更新',
        'date_basis': '秋茶结束后修剪，广东约10月中下旬；剪后留养越冬芽，不宜过晚以免新芽受冻。',
    },
    {
        'product_id': 'tea', 'phase': '茶园管理期',
        'title': '清园管理', 'category': 'manage', 'priority': 'medium',
        'task_md': '11-15', 'month': 11, 'icon': 'broom',
        'source_key': 'GD-TEA-TG',
        'description': '清理茶园杂草落叶',
        'tip': '深翻土壤破坏害虫越冬场所',
        'date_basis': '11月清园并深翻土壤，破坏害虫越冬场所、减少病源基数。',
    },
    {
        'product_id': 'tea', 'phase': '休眠越冬期',
        'title': '防寒防冻', 'category': 'manage', 'priority': 'medium',
        'task_md': '12-15', 'month': 12, 'icon': 'snowflake',
        'source_key': 'CMA-AGRO',
        'description': '茶树根部培土覆盖',
        'tip': '铺草覆盖保温保湿',
        'date_basis': '广东寒潮多在12月中下旬，茶树根部培土与铺草覆盖须在寒潮到来前完成。',
    },
    {
        'product_id': 'vegetable', 'phase': '越冬期',
        'title': '大棚育苗', 'category': 'manage', 'priority': 'high',
        'task_md': '01-10', 'month': 1, 'icon': 'seedling',
        'source_key': 'GD-VEG-TG',
        'description': '利用大棚培育早春蔬菜苗',
        'tip': '保持棚内温度15-25℃',
        'date_basis': '早春瓜豆类苗龄30–35天，按3月中下旬定植倒推，须在1月上中旬播种。',
    },
    {
        'product_id': 'vegetable', 'phase': '春茬期',
        'title': '整地施基肥', 'category': 'fertilize', 'priority': 'high',
        'task_md': '02-10', 'month': 2, 'icon': 'mountain',
        'source_key': 'GD-FERT-GUIDE',
        'description': '深翻土地，施足基肥',
        'tip': '每亩施有机肥2000-3000公斤',
        'date_basis': '定植前20天深翻并施足基肥，使有机肥在定植前充分腐熟分解，避免烧根。',
    },
    {
        'product_id': 'vegetable', 'phase': '春茬期',
        'title': '春季定植', 'category': 'manage', 'priority': 'high',
        'task_md': '03-15', 'month': 3, 'icon': 'exchange-alt',
        'source_key': 'GD-VEG-TG',
        'description': '瓜果类蔬菜定植',
        'tip': '选择晴天下午定植，浇足定根水',
        'date_basis': '广东春茬瓜果类定植期3月中下旬，须日均温稳定15℃以上；选晴天下午定植成活率高。',
    },
    {
        'product_id': 'vegetable', 'phase': '春茬期',
        'title': '田间管理', 'category': 'manage', 'priority': 'medium',
        'task_md': '04-10', 'month': 4, 'icon': 'leaf',
        'source_key': 'GD-VEG-TG',
        'description': '搭架引蔓、整枝打杈',
        'tip': '及时搭架引蔓防止倒伏',
        'date_basis': '定植后25–30天进入搭架引蔓期，广东约4月上中旬，过迟藤蔓已匍匐影响产量。',
    },
    {
        'product_id': 'vegetable', 'phase': '夏茬期',
        'title': '病虫害防治', 'category': 'pest', 'priority': 'high',
        'task_md': '05-10', 'month': 5, 'icon': 'shield-virus',
        'source_key': 'MOA-PEST-MON',
        'description': '防治蚜虫、白粉病',
        'tip': '优先使用黄板+生物农药',
        'date_basis': '5月升温并进入雨季，蚜虫与白粉病进入高发初期，须在流行前介入。',
    },
    {
        'product_id': 'vegetable', 'phase': '夏茬期',
        'title': '夏季遮阳', 'category': 'manage', 'priority': 'high',
        'task_md': '06-10', 'month': 6, 'icon': 'umbrella-beach',
        'source_key': 'GD-VEG-TG',
        'description': '覆盖遮阳网降温',
        'tip': '遮光率50-60%的遮阳网',
        'date_basis': '6月起强光高温，遮阳网须在盛夏到来前覆盖，遮光率50–60%为宜。',
    },
    {
        'product_id': 'vegetable', 'phase': '夏茬期',
        'title': '秋茬育苗', 'category': 'manage', 'priority': 'medium',
        'task_md': '07-05', 'month': 7, 'icon': 'seedling',
        'source_key': 'GD-VEG-TG',
        'description': '7月上旬播种，培育8月定植的秋茬壮苗',
        'tip': '苗床遮阳降温、防暴雨冲刷，培育矮壮苗',
        'date_basis': '秋茬定植安排在8月，叶菜类苗龄约25–30天，故播种须落在7月上旬；过晚则苗龄不足、定植后遇高温死苗率明显上升。',
    },
    {
        'product_id': 'vegetable', 'phase': '夏茬期',
        'title': '灌溉管理', 'category': 'water', 'priority': 'high',
        'task_md': None, 'month': 7, 'icon': 'tint',
        'source_key': 'GD-VEG-TG',
        'description': '早晚灌溉，避免中午浇水',
        'tip': '滴灌或喷灌节水高效',
        'date_basis': '灌溉为持续性作业：夏季需早晚灌溉且避开中午高温，无固定单一日期。',
    },
    {
        'product_id': 'vegetable', 'phase': '秋茬期',
        'title': '秋播准备', 'category': 'manage', 'priority': 'medium',
        'task_md': '08-10', 'month': 8, 'icon': 'seedling',
        'source_key': 'GD-VEG-TG',
        'description': '准备秋播蔬菜种子和育苗',
        'tip': '选择耐热品种进行秋播',
        'date_basis': '广东秋茬菜心、叶菜适期8月中下旬定植，须提前备种育苗并选用耐热品种。',
    },
    {
        'product_id': 'vegetable', 'phase': '秋茬期',
        'title': '秋季定植', 'category': 'manage', 'priority': 'high',
        'task_md': '09-15', 'month': 9, 'icon': 'exchange-alt',
        'source_key': 'GD-VEG-TG',
        'description': '叶菜类、根菜类定植',
        'tip': '适当密植提高产量',
        'date_basis': '广东秋茬叶菜类、根菜类适期9月中下旬定植，此时气温回落、病虫害减轻。',
    },
    {
        'product_id': 'vegetable', 'phase': '秋茬期',
        'title': '采收上市', 'category': 'harvest', 'priority': 'high',
        'task_md': '10-20', 'month': 10, 'icon': 'shopping-basket',
        'source_key': 'GD-VEG-TG',
        'description': '秋季蔬菜大量上市',
        'tip': '适时采收保证品质和口感',
        'date_basis': '秋茬叶菜定植后35–45天采收，对应10月中下旬；适时采收保证品质与口感。',
    },
    {
        'product_id': 'vegetable', 'phase': '越冬期',
        'title': '大棚蔬菜管理', 'category': 'manage', 'priority': 'medium',
        'task_md': '11-15', 'month': 11, 'icon': 'warehouse',
        'source_key': 'CMA-AGRO',
        'description': '覆盖大棚膜，保温促长',
        'tip': '注意通风排湿预防灰霉病',
        'date_basis': '广东11月中下旬气温明显下降，须及时覆膜保温，并注意通风排湿预防灰霉病。',
    },
    {
        'product_id': 'vegetable', 'phase': '越冬期',
        'title': '越冬蔬菜管理', 'category': 'manage', 'priority': 'medium',
        'task_md': '12-10', 'month': 12, 'icon': 'snowflake',
        'source_key': 'CMA-AGRO',
        'description': '加强保温，减少通风',
        'tip': '多层覆盖保温，寒潮时加温',
        'date_basis': '12月中旬起寒潮频繁，须采用多层覆盖保温，极端低温时补充加温。',
    },
    # ==================== v3 新增：柑橘 ====================
    {
        'product_id': 'citrus', 'phase': '花芽分化与越冬期',
        'title': '越冬清园', 'category': 'manage', 'priority': 'high',
        'task_md': '01-08', 'month': 1, 'icon': 'broom',
        'source_key': 'GD-CITRUS-TG',
        'description': '清除落叶、病果、枯枝，集中处理，压低越冬病虫基数',
        'tip': '清园后全园喷施一次石硫合剂，兼顾杀灭越冬螨类与病菌',
        'date_basis': '越冬病虫处于休眠或滞育状态、抗性最弱且尚未开始活动，此期清园可显著压低全年发生基数；广东1月气温最低，作业对树体影响最小。',
    },
    {
        'product_id': 'citrus', 'phase': '花芽分化与越冬期',
        'title': '防寒与树干涂白', 'category': 'manage', 'priority': 'medium',
        'task_md': '01-18', 'month': 1, 'icon': 'snowflake',
        'source_key': 'CMA-AGRO',
        'description': '树干涂白、根颈培土，寒潮前灌水保温',
        'tip': '幼树可覆盖防草布或薄膜，根颈是柑橘最易受冻的部位',
        'date_basis': '广东寒潮集中在1月中下旬，防寒措施须在降温前落地；幼树与树体根颈耐寒性最差，应优先防护。',
    },
    {
        'product_id': 'citrus', 'phase': '现蕾开花期',
        'title': '春梢催芽肥', 'category': 'fertilize', 'priority': 'high',
        'task_md': '02-12', 'month': 2, 'icon': 'seedling',
        'source_key': 'GD-FERT-GUIDE',
        'description': '施速效氮磷钾，促发健壮春梢',
        'tip': '挂果树以磷钾为主，避免偏施氮肥引起梢果矛盾',
        'date_basis': '春梢既是当年主要结果枝也是主要营养枝，须在萌芽前施下催芽肥才能及时供应；广东柑橘春梢多在2月中下旬萌发。',
    },
    {
        'product_id': 'citrus', 'phase': '现蕾开花期',
        'title': '花前病虫防治', 'category': 'pest', 'priority': 'high',
        'task_md': '03-05', 'month': 3, 'icon': 'shield-virus',
        'source_key': 'MOA-PEST-MON',
        'description': '重点防治柑橘木虱、花蕾蛆与炭疽病',
        'tip': '开花期尽量不用药，防治须前移到花蕾期完成',
        'date_basis': '柑橘木虱是黄龙病唯一的田间传播媒介，春季成虫活动始期是压低虫口、切断传播的关键窗口；且开花期施药会伤及授粉昆虫，故必须前移。',
    },
    {
        'product_id': 'citrus', 'phase': '现蕾开花期',
        'title': '保花保果', 'category': 'fertilize', 'priority': 'medium',
        'task_md': '03-25', 'month': 3, 'icon': 'hand-holding-heart',
        'source_key': 'CARS-CITRUS',
        'description': '谢花后喷施磷酸二氢钾与硼肥，提高坐果率',
        'tip': '谢花后一周内完成首次保果，阴雨天气应避开盛花期施药',
        'date_basis': '谢花后即进入第一次生理落果，保花保果措施须在落果高峰前完成，过晚效果明显下降。',
    },
    {
        'product_id': 'citrus', 'phase': '保果膨果期',
        'title': '稳果肥施用', 'category': 'fertilize', 'priority': 'high',
        'task_md': '04-15', 'month': 4, 'icon': 'fill-drip',
        'source_key': 'GD-FERT-GUIDE',
        'description': '第一次生理落果后施稳果肥，配合灌水',
        'tip': '以钾肥为主，控制氮肥用量，防止夏梢猛发',
        'date_basis': '第一次生理落果结束至第二次落果前是稳果关键期，此时补充养分可减少落果；过早施氮会加剧梢果争肥。',
    },
    {
        'product_id': 'citrus', 'phase': '保果膨果期',
        'title': '控夏梢', 'category': 'manage', 'priority': 'high',
        'task_md': '05-10', 'month': 5, 'icon': 'cut',
        'source_key': 'CARS-CITRUS',
        'description': '抹除过旺夏梢，减少梢果争肥',
        'tip': '挂果树以控为主，幼树以放梢扩大树冠为主，两者目不同',
        'date_basis': '夏梢抽发期与幼果发育期重叠，夏梢过旺会与幼果争夺养分并引起大量落果，故须在夏梢抽发初期及时控制。',
    },
    {
        'product_id': 'citrus', 'phase': '保果膨果期',
        'title': '排水防涝', 'category': 'water', 'priority': 'high',
        'task_md': '06-12', 'month': 6, 'icon': 'tint',
        'source_key': 'CMA-AGRO',
        'description': '疏通果园排水沟，防止涝害与根腐',
        'tip': '平地园宜起垄栽培，雨后及时排干积水',
        'date_basis': '广东6月进入降水集中期，柑橘根系怕渍，积水数天即可导致落叶落果，须在雨季前疏通排水系统。',
    },
    {
        'product_id': 'citrus', 'phase': '保果膨果期',
        'title': '柑橘木虱监测防治', 'category': 'pest', 'priority': 'high',
        'task_md': '06-25', 'month': 6, 'icon': 'bug',
        'source_key': 'MOA-PEST-MON',
        'description': '夏梢期加强木虱监测，发现即治',
        'tip': '连片统一用药效果更好，单家独户防治难以压低虫口',
        'date_basis': '夏梢期是木虱繁殖高峰之一，虫口密度上升快；此期防治直接关系黄龙病的传播风险。',
    },
    {
        'product_id': 'citrus', 'phase': '保果膨果期',
        'title': '果实膨大期追肥', 'category': 'fertilize', 'priority': 'high',
        'task_md': '07-10', 'month': 7, 'icon': 'apple-alt',
        'source_key': 'GD-FERT-GUIDE',
        'description': '施壮果肥，促进果实膨大',
        'tip': '配合叶面补充钙肥，减少裂果与浮皮',
        'date_basis': '7月果实进入快速膨大期，养分需求量大；此时补钾补钙可提高单果重，并降低裂果与浮皮发生。',
    },
    {
        'product_id': 'citrus', 'phase': '秋梢抽发期',
        'title': '放秋梢', 'category': 'manage', 'priority': 'high',
        'task_md': '08-10', 'month': 8, 'icon': 'seedling',
        'source_key': 'CARS-CITRUS',
        'description': '统一放秋梢，培养次年结果母枝',
        'tip': '放梢前约10天施攻梢肥，使梢期整齐便于统一防治',
        'date_basis': '秋梢是广东柑橘的主要结果母枝，须在立秋前后统一放梢，使梢期整齐、便于统一防治并确保越冬前老熟。',
    },
    {
        'product_id': 'citrus', 'phase': '秋梢抽发期',
        'title': '柑橘潜叶蛾防治', 'category': 'pest', 'priority': 'high',
        'task_md': '09-05', 'month': 9, 'icon': 'shield-virus',
        'source_key': 'MOA-PEST-MON',
        'description': '秋梢抽发期重点防治柑橘潜叶蛾',
        'tip': '只在嫩梢期用药，梢老熟后防治即基本无效',
        'date_basis': '潜叶蛾仅取食嫩梢，须在秋梢抽发初期（梢长约1–3厘米）用药；梢老熟后幼虫已潜叶为害，再用药效果甚微。',
    },
    {
        'product_id': 'citrus', 'phase': '秋梢抽发期',
        'title': '秋梢壮梢肥', 'category': 'fertilize', 'priority': 'medium',
        'task_md': '09-25', 'month': 9, 'icon': 'fill-drip',
        'source_key': 'GD-FERT-GUIDE',
        'description': '促进秋梢老熟，积累养分',
        'tip': '叶面喷施磷酸二氢钾可加快枝梢老熟',
        'date_basis': '秋梢须在入冬前充分老熟才能顺利进入花芽分化，9月下旬补施磷钾可加速老熟、提高枝梢质量。',
    },
    {
        'product_id': 'citrus', 'phase': '秋梢抽发期',
        'title': '晚秋梢控制', 'category': 'manage', 'priority': 'medium',
        'task_md': '10-20', 'month': 10, 'icon': 'cut',
        'source_key': 'CARS-CITRUS',
        'description': '控制晚秋梢与冬梢，避免无谓消耗养分',
        'tip': '疏除过迟抽发的嫩梢，减少越冬病虫附着',
        'date_basis': '10月以后抽发的晚秋梢难以在越冬前老熟，既消耗树体养分又易受冻并成为病虫越冬场所，故须及时抹除。',
    },
    {
        'product_id': 'citrus', 'phase': '成熟采收期',
        'title': '果实采收', 'category': 'harvest', 'priority': 'high',
        'task_md': '11-15', 'month': 11, 'icon': 'shopping-basket',
        'source_key': 'GD-CITRUS-TG',
        'description': '分批采收成熟果实，轻拿轻放',
        'tip': '采前适当控水可提高耐贮性；雨天不宜采果',
        'date_basis': '广东砂糖橘、贡柑等自11月起陆续成熟，分批采收可兼顾果实品质与树势恢复；采前控水利于提高耐贮性。',
    },
    {
        'product_id': 'citrus', 'phase': '成熟采收期',
        'title': '采后恢复肥', 'category': 'fertilize', 'priority': 'high',
        'task_md': '11-25', 'month': 11, 'icon': 'recycle',
        'source_key': 'GD-FERT-GUIDE',
        'description': '施采后肥，恢复树势',
        'tip': '以有机肥配合复合肥为主，避免单施速效氮',
        'date_basis': '采果后树体养分大量消耗，须及时补充以恢复树势并支撑花芽分化；广东采后至花芽分化间隔短，宜尽早施下。',
    },
    {
        'product_id': 'citrus', 'phase': '花芽分化与越冬期',
        'title': '花芽分化期控水控氮', 'category': 'water', 'priority': 'high',
        'task_md': '12-10', 'month': 12, 'icon': 'hand-paper',
        'source_key': 'CARS-CITRUS',
        'description': '适度控水控氮，促进花芽分化',
        'tip': '弱树与幼树不宜过度控水，否则易伤树',
        'date_basis': '柑橘花芽分化需要适度水分胁迫与较低的碳氮比环境；广东12月气温下降且相对干燥，适度控水控氮有利于成花，控过头则伤树。',
    },
    {
        'product_id': 'citrus', 'phase': '花芽分化与越冬期',
        'title': '冬季清园与病株处理', 'category': 'manage', 'priority': 'high',
        'task_md': '12-25', 'month': 12, 'icon': 'broom',
        'source_key': 'GD-CITRUS-TG',
        'description': '修剪病虫枝，全园清园消毒',
        'tip': '发现黄龙病病株应及时挖除并销毁，不宜留桩或补种同园',
        'date_basis': '冬季是清除黄龙病病株的最佳时期：此时病株症状表现明显、木虱活动弱，及时挖除可最大程度减少翌年传染源。',
    },
    # ==================== v3 新增：香蕉 ====================
    {
        'product_id': 'banana', 'phase': '越冬与花芽分化期',
        'title': '越冬防寒', 'category': 'manage', 'priority': 'high',
        'task_md': '12-10', 'month': 12, 'icon': 'snowflake',
        'source_key': 'CMA-AGRO',
        'description': '蕉园防寒，覆盖蕉头与幼株',
        'tip': '寒潮前灌水、必要时熏烟；寒后及时割除受冻叶片并追肥',
        'date_basis': '香蕉是热带果树，较低温度即造成寒害，广东12月至次年2月为低温期，防护须在寒潮到来前完成。',
    },
    {
        'product_id': 'banana', 'phase': '越冬与花芽分化期',
        'title': '越冬蕉园清理', 'category': 'manage', 'priority': 'medium',
        'task_md': '01-10', 'month': 1, 'icon': 'broom',
        'source_key': 'GD-BANANA-TG',
        'description': '割除枯叶病叶，清理蕉园',
        'tip': '枯叶集中处理，可减少叶斑病与象甲的藏匿场所',
        'date_basis': '越冬期植株生长基本停滞，是清理枯叶病叶、压低叶斑病与象甲基数成本最低的时期。',
    },
    {
        'product_id': 'banana', 'phase': '越冬与花芽分化期',
        'title': '春前施基肥', 'category': 'fertilize', 'priority': 'high',
        'task_md': '02-15', 'month': 2, 'icon': 'seedling',
        'source_key': 'GD-FERT-GUIDE',
        'description': '施有机肥与复合肥，为回暖后快速生长储备养分',
        'tip': '沿蕉头周围开环状沟或放射沟施入后覆土',
        'date_basis': '广东2月下旬气温回升、香蕉恢复生长，基肥须在恢复生长前施下并留出分解时间，才能及时供肥。',
    },
    {
        'product_id': 'banana', 'phase': '春植与苗期管理',
        'title': '春植定植', 'category': 'manage', 'priority': 'high',
        'task_md': '03-10', 'month': 3, 'icon': 'seedling',
        'source_key': 'GD-BANANA-TG',
        'description': '春植蕉定植，选用无病健壮组培苗',
        'tip': '避免连作；前作为茄科作物或已发生枯萎病的蕉园不宜继续种植',
        'date_basis': '广东春植蕉多在2–4月定植，此时地温回升、雨水渐多，成活率高；过早易受低温影响，过晚则缩短生长期、影响当年产量。',
    },
    {
        'product_id': 'banana', 'phase': '春植与苗期管理',
        'title': '选留吸芽', 'category': 'manage', 'priority': 'high',
        'task_md': '03-25', 'month': 3, 'icon': 'cut',
        'source_key': 'CARS-BANANA',
        'description': '宿根蕉选留健壮吸芽，除去多余芽',
        'tip': '每株留1个壮芽，留芽位置以靠近地面、朝向便于管理的方向为宜',
        'date_basis': '宿根蕉靠吸芽更新换代，留芽过早会与母株争肥、过晚则生长量不足；3月留芽可使吸芽在当年形成有效产量。',
    },
    {
        'product_id': 'banana', 'phase': '春植与苗期管理',
        'title': '苗期追肥', 'category': 'fertilize', 'priority': 'medium',
        'task_md': '04-10', 'month': 4, 'icon': 'fill-drip',
        'source_key': 'GD-FERT-GUIDE',
        'description': '薄施勤施，促进蕉苗生长',
        'tip': '浓度宜低、次数宜多，避免一次重肥烧根',
        'date_basis': '香蕉根系浅、耐肥力弱，苗期宜少量多次追肥；一次重肥易造成烧根与肥害。',
    },
    {
        'product_id': 'banana', 'phase': '营养生长期',
        'title': '蕉园培土与除草', 'category': 'manage', 'priority': 'medium',
        'task_md': '05-10', 'month': 5, 'icon': 'tools',
        'source_key': 'GD-BANANA-TG',
        'description': '培土护根，清除杂草',
        'tip': '培土不宜过深，避免埋没蕉头影响呼吸',
        'date_basis': '香蕉为浅根性作物，雨季前培土可防根系外露与植株倒伏，同时清除与蕉争肥的杂草。',
    },
    {
        'product_id': 'banana', 'phase': '营养生长期',
        'title': '排水防涝', 'category': 'water', 'priority': 'high',
        'task_md': '06-15', 'month': 6, 'icon': 'tint',
        'source_key': 'CMA-AGRO',
        'description': '疏通排水沟，防止蕉园积水',
        'tip': '蕉园忌渍水，积水时间长会造成烂根与叶片发黄',
        'date_basis': '广东6月降水集中，香蕉根系不耐渍，积水会造成烂根、叶片发黄甚至死株，须在雨季前完善排水系统。',
    },
    {
        'product_id': 'banana', 'phase': '营养生长期',
        'title': '香蕉象甲防治', 'category': 'pest', 'priority': 'high',
        'task_md': '06-25', 'month': 6, 'icon': 'bug',
        'source_key': 'MOA-PEST-MON',
        'description': '防治香蕉假茎象甲与球茎象甲',
        'tip': '及时清除受害株与残体，避免连作加重虫源积累',
        'date_basis': '象甲在高温多雨的夏季活动与繁殖最盛，成虫多在假茎与球茎取食，此期是压低虫口的关键窗口。',
    },
    {
        'product_id': 'banana', 'phase': '抽蕾与断蕾期',
        'title': '抽蕾期追肥', 'category': 'fertilize', 'priority': 'high',
        'task_md': '07-10', 'month': 7, 'icon': 'seedling',
        'source_key': 'GD-FERT-GUIDE',
        'description': '施抽蕾肥，满足抽蕾与果实发育需要',
        'tip': '以钾肥为主，配合适量氮磷',
        'date_basis': '抽蕾前后是香蕉需肥高峰期，钾素直接影响果指长度与饱满度；须在抽蕾前施下才能及时供应。',
    },
    {
        'product_id': 'banana', 'phase': '抽蕾与断蕾期',
        'title': '断蕾与疏果', 'category': 'manage', 'priority': 'high',
        'task_md': '08-15', 'month': 8, 'icon': 'hand-paper',
        'source_key': 'GD-BANANA-TG',
        'description': '抽蕾后断除花轴，疏去尾部发育不良的果指',
        'tip': '断蕾宜选晴天下午进行，伤口愈合快、感染风险低',
        'date_basis': '果穗末端果指发育差、商品价值低，断蕾疏果可使养分集中供应上部果指；晴天下午伤口愈合快，可减少感染。',
    },
    {
        'product_id': 'banana', 'phase': '抽蕾与断蕾期',
        'title': '防风护蕉', 'category': 'manage', 'priority': 'high',
        'task_md': '08-25', 'month': 8, 'icon': 'umbrella-beach',
        'source_key': 'CMA-AGRO',
        'description': '立桩绑绳固定蕉株，台风前加固',
        'tip': '台风后及时扶正倒伏植株并培土，割除撕裂叶片',
        'date_basis': '香蕉植株高、根系浅，抗风能力弱；8–9月是广东台风影响最集中的时段，须在台风季前完成立桩绑绳。',
    },
    {
        'product_id': 'banana', 'phase': '抽蕾与断蕾期',
        'title': '果实发育期追肥', 'category': 'fertilize', 'priority': 'medium',
        'task_md': '09-15', 'month': 9, 'icon': 'apple-alt',
        'source_key': 'GD-FERT-GUIDE',
        'description': '追施钾肥，促进果实充实',
        'tip': '可配合叶面喷施磷酸二氢钾，提高单果重',
        'date_basis': '断蕾后进入果实充实期，钾素需求持续升高；此期追钾可提高单果重与商品品质。',
    },
    {
        'product_id': 'banana', 'phase': '果实发育与采收期',
        'title': '果实采收', 'category': 'harvest', 'priority': 'high',
        'task_md': '10-20', 'month': 10, 'icon': 'shopping-basket',
        'source_key': 'GD-BANANA-TG',
        'description': '按成熟度分批采收，轻拿轻放',
        'tip': '远距离外运的果实在七八成熟时采收，可减少运输损耗',
        'date_basis': '香蕉果实在断蕾后需较长时间发育成熟，广东秋冬蕉自10月起陆续采收；按成熟度分批采收、外运果适当早采可减少损耗。',
    },
    {
        'product_id': 'banana', 'phase': '果实发育与采收期',
        'title': '采收后蕉园处理', 'category': 'manage', 'priority': 'medium',
        'task_md': '11-15', 'month': 11, 'icon': 'recycle',
        'source_key': 'GD-BANANA-TG',
        'description': '砍除已收果的母株，促使吸芽生长',
        'tip': '留桩高度适中，注意保护待留吸芽不受损伤',
        'date_basis': '母株收果后不再结果，长期保留会与吸芽争光争肥；及时砍除可促使下一代吸芽快速生长，缩短下一造周期。',
    },
    {
        'product_id': 'banana', 'phase': '果实发育与采收期',
        'title': '防寒准备', 'category': 'manage', 'priority': 'medium',
        'task_md': '11-25', 'month': 11, 'icon': 'snowflake',
        'source_key': 'CMA-AGRO',
        'description': '储备防寒材料，做好越冬准备',
        'tip': '幼株可套袋或以稻草覆盖蕉头；抽蕾株耐寒性最差，应优先防护',
        'date_basis': '广东12月至次年2月为低温期，防寒物资须在寒潮到来前到位；幼株与抽蕾株耐寒性最差，需优先处置。',
    },
]
