# -*- coding: utf-8 -*-
"""常见病虫害速查 · 实拍图清单（自动生成，请勿手改）。

来源：项目根 pest_images.csv（人填表）
生成：.workbuddy/_pest_img_ingest.py
时间：2026-10-05 11:42
条目：18 条

要增删改图，请改 pest_images.csv 后重跑生成脚本，不要直接编辑本文件。
"""

PEST_IMAGES = {
    'banana_aphid': {
        'file': '/images/pest/banana_aphid.jpg',
        'credit': 'Ben Jobson',
        'license': 'CC BY',
        'caption': '有翅成虫（香蕉交脉蚜 Pentalonia nigronervosa）',
        'source_url': 'https://www.inaturalist.org/observations/381446146',
        'shot_date': '2026-07-14',
        'note': 'iNaturalist 原图，缩放到 1024px 展示',
    },
    'banana_thrips': {
        'file': '/images/pest/banana_thrips.jpeg',
        'credit': '熊盛志',
        'license': 'CC0',
        'caption': '成虫（香蕉蓟马 Thrips hawaiiensis）',
        'source_url': 'https://www.inaturalist.org/observations/152100512',
        'shot_date': '2023-03-24',
        'note': 'iNaturalist 原图，缩放到 1024px 展示',
    },
    'citrus_leafminer': {
        'file': '/images/pest/citrus_leafminer.jpg',
        'credit': 'Lingeshwaran V.J',
        'license': 'CC BY-NC',
        'caption': '成虫（柑橘潜叶蛾 Phyllocnistis citrella）',
        'source_url': 'https://www.inaturalist.org/observations/404112056',
        'shot_date': '2026-09-28',
        'note': '未拍到潜叶虫道；iNaturalist 原图，缩放到 1024px 展示',
    },
    'citrus_psyllid': {
        'file': '/images/pest/citrus_psyllid.jpg',
        'credit': '镜影溪',
        'license': 'CC BY-NC',
        'caption': '成虫，群集于柑橘嫩梢',
        'source_url': 'https://www.inaturalist.org/observations/404711342',
        'shot_date': '2026-04-18',
        'note': 'iNaturalist 原图，缩放到 1024px 展示',
    },
    'longan_scale_insect': {
        'file': '/images/pest/longan_scale_insect.jpg',
        'credit': 'Bonnie Semmling',
        'license': 'CC BY',
        'caption': '桑白盾蚧 Pseudaulacaspis pentagona（龙眼蚧壳虫类群中的一种）',
        'source_url': 'https://www.inaturalist.org/observations/377574861',
        'shot_date': '2026-06-30',
        'note': 'iNaturalist 原图，缩放到 1024px 展示',
    },
    'longan_stink_bug': {
        'file': '/images/pest/longan_stink_bug.jpg',
        'credit': '吳美珠',
        'license': 'CC BY-NC',
        'caption': '成虫（与荔枝蝽为同一物种 Tessaratoma papillosa）',
        'source_url': 'https://www.inaturalist.org/observations/404407545',
        'shot_date': '2026-09-29',
        'note': 'iNaturalist 原图，缩放到 1024px 展示',
    },
    'lychee_fruit_borer': {
        'file': '/images/pest/lychee_fruit_borer.jpg',
        'credit': 'Chih Hao Chen',
        'license': 'CC BY-NC',
        'caption': '幼虫自果蒂蛀入果实内部（红圈为观察者标注）',
        'source_url': 'https://www.inaturalist.org/observations/373148064',
        'shot_date': '2026-06-19',
        'note': 'iNaturalist 原图，缩放到 1024px 展示',
    },
    'lychee_leaf_roller': {
        'file': '/images/pest/lychee_leaf_roller.jpg',
        'credit': 'bigbob222',
        'license': 'CC BY-NC',
        'caption': '成虫 · 荔枝异形小卷蛾 Cryptophlebia ombrodelta（荔枝卷叶虫类群中的一种）',
        'source_url': 'https://www.inaturalist.org/observations/400082349',
        'shot_date': '2026-09-13',
        'note': '未拍到卷叶为害状；iNaturalist 原图，缩放到 1024px 展示',
    },
    'lychee_stink_bug': {
        'file': '/images/pest/lychee_stink_bug.jpg',
        'credit': 'neonicotinoid',
        'license': 'CC BY-NC',
        'caption': '若虫（成虫为黄褐色盾形、腹面覆白色蜡粉）',
        'source_url': 'https://www.inaturalist.org/observations/405787350',
        'shot_date': '2021-05-07',
        'note': 'iNaturalist 原图，缩放到 1024px 展示',
    },
    'rice_leaf_folder': {
        'file': '/images/pest/rice_leaf_folder.jpg',
        'credit': 'Rajiv Thanawala',
        'license': 'CC BY-NC',
        'caption': '成虫（稻纵卷叶螟 Cnaphalocrocis medinalis）',
        'source_url': 'https://www.inaturalist.org/observations/405655753',
        'shot_date': '2026-04-21',
        'note': '未拍到卷叶为害状；iNaturalist 原图，缩放到 1024px 展示',
    },
    'rice_planthopper': {
        'file': '/images/pest/rice_planthopper.jpg',
        'credit': '王琰',
        'license': 'CC BY-NC',
        'caption': '成虫 · 褐飞虱 Nilaparvata lugens（稻飞虱类群中的一种）',
        'source_url': 'https://www.inaturalist.org/observations/321776016',
        'shot_date': '2025-10-17',
        'note': '照片背景非稻田；iNaturalist 原图，缩放到 1024px 展示',
    },
    'rice_stem_borer': {
        'file': '/images/pest/rice_stem_borer.jpg',
        'credit': 'Fernando de Juana',
        'license': 'CC BY-NC',
        'caption': '成虫 · 二化螟 Chilo suppressalis（水稻螟虫类群中的一种）',
        'source_url': 'https://www.inaturalist.org/observations/306965829',
        'shot_date': '2025-08-12',
        'note': 'iNaturalist 原图，缩放到 1024px 展示',
    },
    'tea_black_spiny_whitefly': {
        'file': '/images/pest/tea_black_spiny_whitefly.jpg',
        'credit': 'joneswurf',
        'license': 'CC BY-NC',
        'caption': '若虫/蛹壳群集于叶面，具白色蜡质边缘（茶黑刺粉虱 Aleurocanthus spiniferus）',
        'source_url': 'https://www.inaturalist.org/observations/405455292',
        'shot_date': '2026-10-03',
        'note': 'iNaturalist 原图，缩放到 1024px 展示',
    },
    'tea_leafhopper': {
        'file': '/images/pest/tea_leafhopper.jpg',
        'credit': '王學哲',
        'license': 'CC BY-NC',
        'caption': '成虫（茶小绿叶蝉 Matsumurasca onukii）',
        'source_url': 'https://www.inaturalist.org/observations/280522632',
        'shot_date': '2025-05-03',
        'note': 'iNaturalist 原图，缩放到 1024px 展示',
    },
    'tea_looper': {
        'file': '/images/pest/tea_looper.jpg',
        'credit': 'starwu',
        'license': 'CC BY-NC',
        'caption': '成虫（茶尺蠖 Ectropis obliqua）',
        'source_url': 'https://www.inaturalist.org/observations/304123624',
        'shot_date': '2025-07-31',
        'note': '未拍到幼虫为害状；iNaturalist 原图，缩放到 1024px 展示',
    },
    'tea_tussock_moth': {
        'file': '/images/pest/tea_tussock_moth.jpg',
        'credit': 'machaonvert',
        'license': 'CC BY-NC',
        'caption': '幼虫群集取食叶片（茶毛虫 Arna pseudoconspersa）',
        'source_url': 'https://www.inaturalist.org/observations/400936298',
        'shot_date': '2026-09-17',
        'note': 'iNaturalist 原图，缩放到 1024px 展示',
    },
    'vegetable_aphid': {
        'file': '/images/pest/vegetable_aphid.jpg',
        'credit': 'Fishopedia',
        'license': 'CC BY-NC',
        'caption': '成蚜/若蚜（桃蚜 Myzus persicae，蔬菜蚜虫类群中的一种）',
        'source_url': 'https://www.inaturalist.org/observations/362179044',
        'shot_date': '2026-05-16',
        'note': 'iNaturalist 原图，缩放到 1024px 展示',
    },
    'vegetable_diamondback_moth': {
        'file': '/images/pest/vegetable_diamondback_moth.jpg',
        'credit': 'Hobby📸mit❤️zur Natur',
        'license': 'CC BY-NC',
        'caption': '成虫（小菜蛾 Plutella xylostella）',
        'source_url': 'https://www.inaturalist.org/observations/405610068',
        'shot_date': '2026-10-03',
        'note': '未拍到「开天窗」为害状；iNaturalist 原图，缩放到 1024px 展示',
    },
}
