"""Administrator console foundation package."""

from __future__ import annotations

from app.admin_console.presets import (
    ASSISTANT_FEATURE_KEYS,
    DatabaseCraftPresetProvider,
    create_case_preset,
    create_craft_preset,
    create_knowledge_preset,
    disable_case_preset,
    disable_craft_preset,
    disable_knowledge_preset,
    list_case_presets,
    list_craft_presets,
    list_knowledge_presets,
    seed_assistant_feature_knowledge,
    update_case_preset,
    update_craft_preset,
    update_knowledge_preset,
)
from app.admin_console.providers import (
    AdminDatabaseLocalResourceCaseProvider,
    AssistantFeatureKnowledgeProvider,
    CraftPresetProvider,
    DatabaseAssistantFeatureKnowledgeProvider,
    DatabasePointsPolicyProvider,
    DatabaseRewardCatalogProvider,
    DatabaseFeedbackIntakeProvider,
    FeedbackIntakeProvider,
    LocalResourceCaseProvider,
    PointsPolicyProvider,
    UnavailableAssistantFeatureKnowledgeProvider,
    UnavailableFeedbackIntakeProvider,
    UnavailablePointsPolicyProvider,
    configure_admin_providers,
    get_assistant_feature_knowledge_provider,
    get_feedback_intake_provider,
    get_points_policy_provider,
    install_default_admin_services,
    set_assistant_feature_knowledge_provider,
    set_feedback_intake_provider,
    set_points_policy_provider,
)
from app.admin_console.rewards import (
    create_reward,
    list_reward_reservations,
    list_rewards_admin,
    seed_demo_rewards,
    set_reward_online,
    update_reward,
)
from app.admin_console.points_policy import (
    get_points_policy,
    seed_demo_points_policy,
    update_points_policy,
)
from app.admin_console.routes import (
    admin_console_bp,
    register_admin_console_error_handlers,
    require_admin_session,
)
from app.handcraft_inheritance.providers import (
    get_craft_preset_provider,
)
from app.local_resources.cases import (
    get_local_resource_case_provider,
)


__all__ = [
    "ASSISTANT_FEATURE_KEYS",
    "AdminDatabaseLocalResourceCaseProvider",
    "AssistantFeatureKnowledgeProvider",
    "CraftPresetProvider",
    "DatabaseAssistantFeatureKnowledgeProvider",
    "DatabaseCraftPresetProvider",
    "DatabasePointsPolicyProvider",
    "DatabaseFeedbackIntakeProvider",
    "DatabaseRewardCatalogProvider",
    "FeedbackIntakeProvider",
    "LocalResourceCaseProvider",
    "PointsPolicyProvider",
    "UnavailableAssistantFeatureKnowledgeProvider",
    "UnavailableFeedbackIntakeProvider",
    "UnavailablePointsPolicyProvider",
    "admin_console_bp",
    "configure_admin_providers",
    "create_case_preset",
    "create_reward",
    "create_craft_preset",
    "create_knowledge_preset",
    "disable_case_preset",
    "disable_craft_preset",
    "disable_knowledge_preset",
    "get_assistant_feature_knowledge_provider",
    "get_craft_preset_provider",
    "get_feedback_intake_provider",
    "get_local_resource_case_provider",
    "get_points_policy",
    "get_points_policy_provider",
    "install_default_admin_services",
    "list_reward_reservations",
    "list_rewards_admin",
    "list_case_presets",
    "list_craft_presets",
    "list_knowledge_presets",
    "register_admin_console_error_handlers",
    "require_admin_session",
    "seed_assistant_feature_knowledge",
    "seed_demo_rewards",
    "seed_demo_points_policy",
    "set_reward_online",
    "set_assistant_feature_knowledge_provider",
    "set_feedback_intake_provider",
    "set_points_policy_provider",
    "update_case_preset",
    "update_craft_preset",
    "update_knowledge_preset",
    "update_points_policy",
    "update_reward",
]
